language: csharp
solution: ModernPlayerManagementAPI.sln
mono: none
dotnet: 3.1.201
install:
- dotnet restore
script:
- dotnet build
- dotnet test ModernPlayerManagementAPITests/ModernPlayerManagementAPITests.csproj