language: csharp
solution: ModernPlayerManagementAPI.sln
mono: none
dotnet: 3.1.201
install:
- dotnet restore
script:
- dotnet build
- dotnet test ModernPlayerManagementAPITests/ModernPlayerManagementAPITests.csproj

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: eu-west-3
  app: apimodernplayermanager
  env: apimodernplayermanager-env
  bucket_name: elasticbeanstalk-eu-west-3-689693283697
  on:
    branch: master

after_success:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

