language: csharp
solution: ModernPlayerManagementAPI.sln
mono: none
dotnet: 3.1.201
install:
- dotnet restore
script:
- dotnet build
- dotnet test ModernPlayerManagementAPITests/ModernPlayerManagementAPITests.csproj

after_success:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/LacazeThomas/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh $WEBHOOK_URL